MODEL:
  model_names: xxx
  model_spec: xx

  load_Pretraining: "./waletnet_imagenet_1K.ckpt"

DATASET:
  dataset: New_PolypDataset
  name: New_PolypDataset
  dataroot: "./dataset/New_PolypVideoDataset/"
  ignore_index: 255
  num_labels: 3
  mean: [0.49653283, 0.3011748, 0.21566062]
  std: [0.29782128, 0.20789528, 0.16115053]
  Low_mean: [0.219539]
  Low_std: [0.201081]
  High_mean: [-0.411374]
  High_std: [0.031889]

TRAIN:
  nepoch: 5
  batch_size: 12
  size: [576, 720]
  num_workers: 6
  eval_interval: 2
  checkpoints_dir: "checkpoints"
  node: 1

OPTIMIZER:
  lr: 0.00006
  weight_decay: 0.05

SCHEDULER:
  warmup_epoch: 5
  lr_warmup: linear
  warmup_ratio: 0.000001

continue_train: False
